INSERT INTO dbo.Categoria (Nome) VALUES ('RPG')
INSERT INTO dbo.Categoria (Nome) VALUES ('Corrida')
INSERT INTO dbo.Categoria (Nome) VALUES ('Aventura')
INSERT INTO dbo.Categoria (Nome) VALUES ('Luta')
INSERT INTO dbo.Categoria (Nome) VALUES ('Esporte')

INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Chrono Trigger',1, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Top Gear',2, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Megaman X',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Super Metroid',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Donkey Kong Country',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Super Mario Kart',2, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Super Street Fighter',4, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Mortal Kombat 2',4, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Killer Instinct',4, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Final Fight',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Super Mario 1',1, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Aladdin',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Rock ''n Roll Racing',2, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Zelda: A link to the past',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Final Fantasy VI',1, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('International Super Star Soccer Deluxe',5, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Contra III',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Sunset Riders',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Goof Troop',3, 'Sem descrição', 1)
INSERT INTO dbo.Jogo (Nome, IdCategoria, Descricao, IdSelo) VALUES ('Mickey to Donald: Magical Adventure 3',3, 'Sem descrição', 1)